// src/proposal/NearProposals.vue
<script setup lang="ts">
import { SlotType, isLunch, isDinner } from "@/proposal/domain/slot";

defineProps<{ slotType: SlotType }>();
</script>

<template>
  <article>
    <h1 v-if="isLunch(slotType)">Prochain midi</h1>
    <h1 v-if="isDinner(slotType)">Prochain afterwork</h1>

    <strong v-if="isLunch(slotType)">Aucun midi disponible</strong>
    <strong v-if="isDinner(slotType)">Aucun afterwork disponible</strong>
  </article>
</template>

// src/proposal/containers/NearProposals.tsx
import React from 'react';
import { Proposals } from '../domain/proposal';
import { useNearProposals } from '../hooks/useNearProposals';
import { ProposalCard } from '../components/ProposalCard';

export const NearProposals: React.FC = () => {
  const proposals: Proposals = useNearProposals();

  return (
    <>
      <h1>Prochain midi</h1>
      {proposals.length === 0 ? (
        <span>Aucun midi disponible</span>
      ) : (
        proposals.map((proposal) => <ProposalCard proposal={proposal} key={proposal.id} />)
      )}
      {}
    </>
  );
};
